language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  - echo -e "[server]\nwait_timeout=28800" | sudo tee -a /etc/mysql/my.cnf
  - cat /etc/mysql/my.cnf
  - sudo service mysql restart	  
  - cat sql/hungry.sql
  - mysql --user="root" --password="" < "sql/hungry.sql"
  - mysql --user="root" --database="hungrydatabase" --password="" < "sql/hungryTest.sql"
  - mysql --user="root" --database="hungrydatabase" --password="" --execute="SELECT * FROM Users"
  
