language: java

before_install:
  - mvn -version
  - pwd
  - ls -a /home/travis
  - ls -a /home/travis/build
  
install:
  - sudo apt-get install systemd
  - sudo bash set_up_server.sh
  - printenv 

before_script:
  - sudo bash set_up_database.sh

after_script:
  - mvn -version
  - mvn -Dmaven.test.skip=true package
  - sudo bash deploy_application.sh
