language: java

before_install:
  - pwd
  - printenv 
  - ls -a /home/travis
  - ls -a /home/travis/build
  
install:
  - sudo apt-get install systemd
  - sudo bash set_up_server.sh

before_script:
  - sudo bash set_up_database.sh

after_script:
  - sudo bash deploy_application.sh
