language: java

before_script:
  - echo -e "[server]\nwait_timeout=28800" | sudo tee -a /etc/mysql/my.cnf
  - cat /etc/mysql/my.cnf
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE hungrydatabase;'
  - ls
  - mysql < AlexColello/CS310GroupC/sql/hungry.sql
