
matrix:
  include:
    - language: java
        
      install:
        - sudo apt-get install systemd

      before_script:
        - sudo bash set_up_database.sh
        
    - language: ruby
      cache: bundler

      dist: trusty

      addons:
        chrome: stable

      rvm:
        - 1.9.3

      before_install:
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

      install:
        - sudo apt-get install systemd
        - sudo bash set_up_server.sh

      before_script:
        - sudo bash set_up_database.sh
        - mvn -Dmaven.test.skip=true package
        - sudo bash deploy_application.sh
      before_script: 
        - cd /home/travis/build/AlexColello/CS310GroupC/src/test/ImHungryCucumber
        - bundle install
      script: 
        - bundle exec cucumber
