language: java

before_install:
  - ls /usr/java/
  - ls /usr/java/apache-maven-3.0.3/conf
  - pwd

install:
  - sudo apt-get install systemd
  - sudo bash set_up_server.sh

before_script:
  - sudo bash set_up_database.sh
  - sudo bash deploy_application.sh
