language: java

before_install:
  - pwd

install:
  - sudo apt-get install systemd
  - sudo bash set_up_server.sh

before_script:
  - sudo bash set_up_database.sh
  - sudo bash deploy_application.sh

