language: java

before_install:
  - pwd
  - ls -a /home/travis
  - ls -a /home/travis/build
  

install:
  - sudo apt-get install systemd
  - sudo bash set_up_server.sh

before_script:
  - sudo bash set_up_database.sh
  - sudo bash deploy_application.sh
