
matrix:
  include:
    - language: java
        
      before_script:
        - sudo bash set_up_database.sh
        
    - language: ruby
      cache: bundler

      dist: trusty

      addons:
        chrome: stable

      rvm:
        - 2.6.2

      before_install:
        - ls /usr/lib

      install:
        - sudo apt-get install systemd
        - sudo bash set_up_server.sh

      before_script:
        - sudo bash set_up_database.sh
        - mvn -Dmaven.test.skip=true package
        - sudo bash deploy_application.sh
      before_script: 
        - cd /home/travis/build/AlexColello/CS310GroupC/src/test/ImHungryCucumber
        - bundle install
      script: 
        - bundle exec cucumber
