language: java

before_install:
  - sudo apt-get install systemd
  - sudo bash set_up_server.sh

install:
  - ls -a
  - sudo bash deploy_application.sh

before_script:
  - sudo bash set_up_database.sh
