language: java

before_script:
  - echo -e "[server]\nwait_timeout=28800" | sudo tee -a /etc/mysql/my.cnf
  - cat /etc/mysql/my.cnf
  - mysql -e 'CREATE DATABASE IF NOT EXISTS HungryDatabase;'
  - sudo service mysql restart
  - cat sql/hungry.sql
  - mysql < sql/hungry.sql
  - sudo service mysql restart
